version: '3.8'

services:
  # Base de Datos Relacional
  postgres:
    image: postgres:16
    container_name: munify-db-v2
    environment:
      POSTGRES_USER: munify_user
      POSTGRES_PASSWORD: munify_password
      POSTGRES_DB: munify_db
    ports:
      - "5433:5432"
    networks:
      - munify-network

  # Cache y Mensajería Real-time
  redis:
    image: redis:latest
    container_name: munify-redis
    ports:
      - "6379:6379"
    networks:
      - munify-network

networks:
  munify-network:
    driver: bridge
